In [2]:
import pandas as pd

In [4]:
accout_data_train = pd.read_json(r'E:\senior_ds_test\senior_ds_test\data\train\accounts_data_train.json')
enquiry_data_train = pd.read_json(r'E:\senior_ds_test\senior_ds_test\data\train\enquiry_data_train.json')
train_flag = pd.read_csv(r'E:\senior_ds_test\senior_ds_test\data\train\train_flag.csv')

In [8]:
enquiry_data_train

,0,1,2,3,4,5,6,7,8,9,...,59,60,61,62,63,64,65,66,67,68
0,"{'enquiry_type': 'Interbank credit', 'enquiry_...","{'enquiry_type': 'Mobile operator loan', 'enqu...","{'enquiry_type': 'Mobile operator loan', 'enqu...","{'enquiry_type': 'Interbank credit', 'enquiry_...","{'enquiry_type': 'Cash loan (non-earmarked)', ...","{'enquiry_type': 'Mortgage', 'enquiry_amt': 44...","{'enquiry_type': 'Revolving loans', 'enquiry_a...","{'enquiry_type': 'Interbank credit', 'enquiry_...",{'enquiry_type': 'Loan for purchase of shares ...,"{'enquiry_type': 'Revolving loans', 'enquiry_a...",...,None,None,None,None,None,None,None,None,None,None
1,"{'enquiry_type': 'Cash loans', 'enquiry_amt': ...","{'enquiry_type': 'Interbank credit', 'enquiry_...","{'enquiry_type': 'Car loan', 'enquiry_amt': 12...","{'enquiry_type': 'Revolving loans', 'enquiry_a...","{'enquiry_type': 'Car loan', 'enquiry_amt': 12...","{'enquiry_type': 'Another type of loan', 'enqu...",{'enquiry_type': 'Loan for the purchase of equ...,"{'enquiry_type': 'Real estate loan', 'enquiry_...","{'enquiry_type': 'Credit card', 'enquiry_amt':...","{'enquiry_type': 'Unknown type of loan', 'enqu...",...,None,None,None,None,None,None,None,None,None,None
2,"{'enquiry_type': 'Revolving loans', 'enquiry_a...","{'enquiry_type': 'Consumer credit', 'enquiry_a...","{'enquiry_type': 'Interbank credit', 'enquiry_...","{'enquiry_type': 'Revolving loans', 'enquiry_a...",{'enquiry_type': 'Loan for purchase of shares ...,"{'enquiry_type': 'Cash loans', 'enquiry_amt': ...","{'enquiry_type': 'Cash loan (non-earmarked)', ...","{'enquiry_type': 'Another type of loan', 'enqu...","{'enquiry_type': 'Consumer credit', 'enquiry_a...","{'enquiry_type': 'Credit card', 'enquiry_amt':...",...,None,None,None,None,None,None,None,None,None,None
3,{'enquiry_type': 'Loan for purchase of shares ...,{'enquiry_type': 'Loan for working capital rep...,"{'enquiry_type': 'Consumer credit', 'enquiry_a...",{'enquiry_type': 'Loan for the purchase of equ...,"{'enquiry_type': 'Another type of loan', 'enqu...",{'enquiry_type': 'Loan for the purchase of equ...,"{'enquiry_type': 'Unknown type of loan', 'enqu...","{'enquiry_type': 'Cash loan (non-earmarked)', ...","{'enquiry_type': 'Cash loans', 'enquiry_amt': ...","{'enquiry_type': 'Consumer credit', 'enquiry_a...",...,None,None,None,None,None,None,None,None,None,None
4,"{'enquiry_type': 'Mobile operator loan', 'enqu...",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261378,"{'enquiry_type': 'Mortgage', 'enquiry_amt': 61...",{'enquiry_type': 'Loan for the purchase of equ...,{'enquiry_type': 'Loan for business developmen...,"{'enquiry_type': 'Mortgage', 'enquiry_amt': 19...",{'enquiry_type': 'Loan for working capital rep...,"{'enquiry_type': 'Consumer credit', 'enquiry_a...","{'enquiry_type': 'Cash loans', 'enquiry_amt': ...","{'enquiry_type': 'Real estate loan', 'enquiry_...",None,None,...,None,None,None,None,None,None,None,None,None,None
261379,"{'enquiry_type': 'Real estate loan', 'enquiry_...",{'enquiry_type': 'Loan for the purchase of equ...,"{'enquiry_type': 'Real estate loan', 'enquiry_...","{'enquiry_type': 'Mobile operator loan', 'enqu...","{'enquiry_type': 'Credit card', 'enquiry_amt':...",{'enquiry_type': 'Loan for purchase of shares ...,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
261380,"{'enquiry_type': 'Microloan', 'enquiry_amt': 2...",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
261381,"{'enquiry_type': 'Unknown type of loan', 'enqu...",{'enquiry_type': 'Loan for purchase of shares ...,"{'enquiry_type': 'Cash loans', 'enquiry_amt': ...","{'enquiry_type': 'Cash loans', 'enquiry_amt': ...","{'enquiry_type': 'Cash loans', 'enquiry_amt': ...","{'enquiry_type': 'Real estate loan', 'enquiry_...","{'enquiry_type': 'Cash loans', 'enquiry_amt': ...","{'enquiry_type': 'Revolving loans', 'enquiry_a...","{'enquiry_type': 'Real estate loan', 'enquiry_...","{'enquiry_type': 'Car loan', 'enquiry_amt': 61...",...,None,None,None,None,None,None,None,None,None,None
261382,"{'enquiry_type': 'Credit card', 'enquiry_amt':...",{'enquiry_type': 'Loan for the purchase of equ...,"{'enquiry_type': 'Consumer credit', 'enquiry_a...",{'enquiry_type': 'Loan for purchase of shares ...,{'enquiry_type': 'Loan for purchase of shares ...,"{'enquiry_type': 'Real estate loan', 'enquiry_...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [6]:
for df in [accout_data_train,enquiry_data_train,train_flag]:
    print(df.shape)
    display(df.head())

(223918, 116)

,0,1,2,3,4,5,6,7,8,9,...,106,107,108,109,110,111,112,113,114,115
0,"{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...",None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,"{'credit_type': 'Credit card', 'loan_amount': ...",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,"{'credit_type': 'Consumer credit', 'loan_amoun...",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,"{'credit_type': 'Credit card', 'loan_amount': ...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Credit card', 'loan_amount': ...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Credit card', 'loan_amount': ...",None,None,...,None,None,None,None,None,None,None,None,None,None
4,"{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Credit card', 'loan_amount': ...",None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

(261383, 69)

,0,1,2,3,4,5,6,7,8,9,...,59,60,61,62,63,64,65,66,67,68
0,"{'enquiry_type': 'Interbank credit', 'enquiry_...","{'enquiry_type': 'Mobile operator loan', 'enqu...","{'enquiry_type': 'Mobile operator loan', 'enqu...","{'enquiry_type': 'Interbank credit', 'enquiry_...","{'enquiry_type': 'Cash loan (non-earmarked)', ...","{'enquiry_type': 'Mortgage', 'enquiry_amt': 44...","{'enquiry_type': 'Revolving loans', 'enquiry_a...","{'enquiry_type': 'Interbank credit', 'enquiry_...",{'enquiry_type': 'Loan for purchase of shares ...,"{'enquiry_type': 'Revolving loans', 'enquiry_a...",...,None,None,None,None,None,None,None,None,None,None
1,"{'enquiry_type': 'Cash loans', 'enquiry_amt': ...","{'enquiry_type': 'Interbank credit', 'enquiry_...","{'enquiry_type': 'Car loan', 'enquiry_amt': 12...","{'enquiry_type': 'Revolving loans', 'enquiry_a...","{'enquiry_type': 'Car loan', 'enquiry_amt': 12...","{'enquiry_type': 'Another type of loan', 'enqu...",{'enquiry_type': 'Loan for the purchase of equ...,"{'enquiry_type': 'Real estate loan', 'enquiry_...","{'enquiry_type': 'Credit card', 'enquiry_amt':...","{'enquiry_type': 'Unknown type of loan', 'enqu...",...,None,None,None,None,None,None,None,None,None,None
2,"{'enquiry_type': 'Revolving loans', 'enquiry_a...","{'enquiry_type': 'Consumer credit', 'enquiry_a...","{'enquiry_type': 'Interbank credit', 'enquiry_...","{'enquiry_type': 'Revolving loans', 'enquiry_a...",{'enquiry_type': 'Loan for purchase of shares ...,"{'enquiry_type': 'Cash loans', 'enquiry_amt': ...","{'enquiry_type': 'Cash loan (non-earmarked)', ...","{'enquiry_type': 'Another type of loan', 'enqu...","{'enquiry_type': 'Consumer credit', 'enquiry_a...","{'enquiry_type': 'Credit card', 'enquiry_amt':...",...,None,None,None,None,None,None,None,None,None,None
3,{'enquiry_type': 'Loan for purchase of shares ...,{'enquiry_type': 'Loan for working capital rep...,"{'enquiry_type': 'Consumer credit', 'enquiry_a...",{'enquiry_type': 'Loan for the purchase of equ...,"{'enquiry_type': 'Another type of loan', 'enqu...",{'enquiry_type': 'Loan for the purchase of equ...,"{'enquiry_type': 'Unknown type of loan', 'enqu...","{'enquiry_type': 'Cash loan (non-earmarked)', ...","{'enquiry_type': 'Cash loans', 'enquiry_amt': ...","{'enquiry_type': 'Consumer credit', 'enquiry_a...",...,None,None,None,None,None,None,None,None,None,None
4,"{'enquiry_type': 'Mobile operator loan', 'enqu...",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

(261383, 3)

           uid NAME_CONTRACT_TYPE  TARGET
0  XDA69787158         Cash loans       0
1  BSE47789733         Cash loans       0
2  NTJ92213825         Cash loans       0
3  TCQ47571695         Cash loans       0
4  WJZ68772744         Cash loans       0

In [10]:
import json
import numpy as np

with open(r'E:\senior_ds_test\senior_ds_test\data\test\accounts_data_test.json') as f:
    acc_raw = json.load(f)

print(type(acc_raw))            # list
print(type(acc_raw[0]))         # list
print(acc_raw[0][0])            # first account of first applicant → a dict
print(len(acc_raw))             # number of applicants

<class 'list'>
<class 'list'>
{'credit_type': 'Consumer credit', 'loan_amount': 31630.5, 'amount_overdue': 0.0, 'open_date': '2014-03-30', 'closed_date': '2014-11-29', 'payment_hist_string': '000000000000000000000000', 'uid': 'AAA14437029'}
39572

In [11]:
import json
import numpy as np

with open(r'E:\senior_ds_test\senior_ds_test\data\test\enquiry_data_test.json') as f:
    enq_raw = json.load(f)

print(type(enq_raw))            # list
print(type(enq_raw[0]))         # list
print(enq_raw[0][0])            # first account of first applicant → a dict
print(len(enq_raw))             # number of applicants

<class 'list'>
<class 'list'>
{'enquiry_type': 'Car loan', 'enquiry_amt': 143000, 'enquiry_date': '2020-12-13', 'uid': 'AAA02107680'}
46127

In [12]:
import json
import pandas as pd
import numpy as np

def load_nested_json(path):
    with open(path) as f:
        raw = json.load(f)
    records = []
    for applicant in raw:          # applicant = list of dicts (or None padding)
        for rec in applicant:
            if rec is not None:
                records.append(rec)
    return pd.DataFrame(records)

# TRAIN
flag_train = pd.read_csv(r'E:\senior_ds_test\senior_ds_test\data\train\train_flag.csv')
acc_train  = load_nested_json(r'E:\senior_ds_test\senior_ds_test\data\train\accounts_data_train.json')
enq_train  = load_nested_json(r'E:\senior_ds_test\senior_ds_test\data\train\enquiry_data_train.json')

In [ ]:
# # TEST
# flag_test  = pd.read_csv('data/test/flag.csv')   # or sample_submission for uids
# acc_test   = load_nested_json('data/test/accounts.json')
# enq_test   = load_nested_json('data/test/enquiry.json')

In [13]:

print(acc_train.shape, acc_train.columns.tolist())
print(enq_train.shape, enq_train.columns.tolist())
print(flag_train.shape, flag_train.columns.tolist())

print("flag applicants :", flag_train['uid'].nunique())
print("acc  applicants :", acc_train['uid'].nunique())   # expect ~39,572
print("enq  applicants :", enq_train['uid'].nunique())   # expect ~46,127

# What fraction of applicants have accounts / enquiries?
print("has accounts  :", flag_train['uid'].isin(acc_train['uid']).mean())
print("has enquiries :", flag_train['uid'].isin(enq_train['uid']).mean())

# Are all acc/enq uids present in flag? (should be)
print("acc uids in flag:", acc_train['uid'].isin(flag_train['uid']).mean())
print("enq uids in flag:", enq_train['uid'].isin(flag_train['uid']).mean())

(1245310, 7) ['credit_type', 'loan_amount', 'amount_overdue', 'open_date', 'closed_date', 'payment_hist_string', 'uid']
(1909926, 4) ['enquiry_type', 'enquiry_amt', 'enquiry_date', 'uid']
(261383, 3) ['uid', 'NAME_CONTRACT_TYPE', 'TARGET']
flag applicants : 261383
acc  applicants : 223918
enq  applicants : 261383
has accounts  : 0.8566662713336368
has enquiries : 1.0
acc uids in flag: 1.0
enq uids in flag: 1.0

In [17]:
enq_train.head()

                enquiry_type  enquiry_amt enquiry_date          uid
0           Interbank credit       168839   2020-11-08  AAA08065248
1       Mobile operator loan       268392   2020-09-20  AAA08065248
2       Mobile operator loan        36082   2020-06-19  AAA08065248
3           Interbank credit       180467   2019-10-22  AAA08065248
4  Cash loan (non-earmarked)       227459   2020-05-24  AAA08065248

In [18]:
# Class balance
print(flag_train['TARGET'].value_counts())
print(flag_train['TARGET'].value_counts(normalize=True))

# Any nulls in target?
print("Target nulls:", flag_train['TARGET'].isna().sum())

# NAME_CONTRACT_TYPE breakdown + default rate by contract type
print(flag_train['NAME_CONTRACT_TYPE'].value_counts())
print(flag_train.groupby('NAME_CONTRACT_TYPE')['TARGET'].mean())

TARGET
0    240326
1     21057
Name: count, dtype: int64
TARGET
0    0.91944
1    0.08056
Name: proportion, dtype: float64
Target nulls: 0
NAME_CONTRACT_TYPE
Cash loans         236524
Revolving loans     24859
Name: count, dtype: int64
NAME_CONTRACT_TYPE
Cash loans         0.083294
Revolving loans    0.054548
Name: TARGET, dtype: float64

In [19]:
# --- Ensure correct dtypes ---
acc = acc_train.copy()
acc['open_date']      = pd.to_datetime(acc['open_date'], errors='coerce')
acc['closed_date']    = pd.to_datetime(acc['closed_date'], errors='coerce')
acc['loan_amount']    = pd.to_numeric(acc['loan_amount'], errors='coerce')
acc['amount_overdue'] = pd.to_numeric(acc['amount_overdue'], errors='coerce')

# --- 2a. Missing values ---
print("MISSING %:\n", acc.isna().mean().round(4))

# --- 2b. Accounts per applicant ---
print("\nACCOUNTS PER APPLICANT:\n", acc.groupby('uid').size().describe())

# --- 2c. credit_type distribution ---
print("\nCREDIT TYPES:\n", acc['credit_type'].value_counts())

# --- 2d. Amount distributions (check skew) ---
print("\nLOAN AMOUNT:\n", acc['loan_amount'].describe())
print("\nAMOUNT OVERDUE:\n", acc['amount_overdue'].describe())
print("\n% accounts with overdue > 0:", (acc['amount_overdue'] > 0).mean())

# --- 2e. Open vs closed loans ---
print("\n% loans still open (closed_date missing):", acc['closed_date'].isna().mean())

# --- 2f. Date ranges (for the reference-date problem) ---
print("\nOPEN DATE range :", acc['open_date'].min(), "→", acc['open_date'].max())
print("CLOSED DATE range:", acc['closed_date'].min(), "→", acc['closed_date'].max())

MISSING %:
 credit_type            0.0000
loan_amount            0.0000
amount_overdue         0.0000
open_date              0.0000
closed_date            0.3718
payment_hist_string    0.0000
uid                    0.0000
dtype: float64

ACCOUNTS PER APPLICANT:
 count    223918.000000
mean          5.561456
std           4.384241
min           1.000000
25%           2.000000
50%           4.000000
75%           8.000000
max         116.000000
dtype: float64

CREDIT TYPES:
 credit_type
Consumer credit                                 908741
Credit card                                     292422
Car loan                                         20237
Mortgage                                         13196
Microloan                                         7766
Loan for business development                     1466
Another type of loan                               732
Unknown type of loan                               374
Loan for working capital replenishment             320
Real estate loan                                    17
Cash loan (non-earmarked)                           17
Loan for the purchase of equipment                  16
Loan for purchase of shares (margin lending)         4
Interbank credit                                     1
Mobile operator loan                                 1
Name: count, dtype: int64

LOAN AMOUNT:
 count    1.245307e+06
mean     3.523541e+05
std      1.109812e+06
min      0.000000e+00
25%      5.114700e+04
50%      1.246590e+05
75%      3.087000e+05
max      3.960000e+08
Name: loan_amount, dtype: float64

AMOUNT OVERDUE:
 count    1.245310e+06
mean     4.202288e+01
std      6.668687e+03
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      3.756681e+06
Name: amount_overdue, dtype: float64

% accounts with overdue > 0: 0.002482112887554103

% loans still open (closed_date missing): 0.37182308019689875

OPEN DATE range : 2013-01-01 00:00:00 → 2021-01-01 00:00:00
CLOSED DATE range: 1905-12-13 00:00:00 → 2021-01-01 00:00:00

In [20]:
# How many garbage closed_dates?
bad = acc['closed_date'] < acc['open_date']
print("closed < open (invalid):", bad.sum(), "→", round(bad.mean()*100,3), "%")

# How many closed_dates before 2013 (impossible given open range)?
print("closed before 2013:", (acc['closed_date'] < '2013-01-01').sum())

# Confirm the hard cap — what's the exact max across all date columns?
print("max open  :", acc['open_date'].max())
print("max closed:", acc['closed_date'].max())

# Any loan_amount == 0?
print("zero loan_amount rows:", (acc['loan_amount']==0).sum())

closed < open (invalid): 13 → 0.001 %
closed before 2013: 2
max open  : 2021-01-01 00:00:00
max closed: 2021-01-01 00:00:00
zero loan_amount rows: 47585

In [21]:
acc = acc_train.copy()  # already loaded
ph = acc['payment_hist_string'].astype(str)

# 3a. Are all lengths divisible by 3? (validates the "3 digits per month" rule)
lengths = ph.str.len()
print("Length stats:\n", lengths.describe())
print("\n% length divisible by 3:", (lengths % 3 == 0).mean())
print("\nLengths NOT divisible by 3 (sample):")
print(ph[lengths % 3 != 0].head(10).tolist())

# 3b. Any empty strings / nulls?
print("\nEmpty strings:", (ph == '').sum())
print("'nan' strings:", (ph == 'nan').sum())

# 3c. Distribution of history length (how many months of history per account)
n_months = lengths // 3
print("\nMONTHS OF HISTORY PER ACCOUNT:\n", n_months.describe())

# 3d. Peek at some actual values to understand the digit patterns
print("\nSample payment histories:")
for s in ph.sample(10, random_state=1).tolist():
    print(repr(s))

# 3e. What digit-values actually appear? Parse a sample into monthly DPD values
def parse_ph(s):
    s = str(s)
    if s in ('', 'nan') or len(s) < 3:
        return []
    return [int(s[i:i+3]) for i in range(0, len(s) - len(s) % 3, 3)]

sample_vals = []
for s in ph.sample(20000, random_state=1):
    sample_vals.extend(parse_ph(s))
sample_vals = pd.Series(sample_vals)
print("\nMonthly DPD value distribution (sampled):")
print(sample_vals.describe())
print("\n% months with DPD>0:", (sample_vals > 0).mean())
print("Max DPD seen:", sample_vals.max())
print("Value counts of top DPD buckets:")
print(pd.cut(sample_vals, [-1,0,29,59,89,119,10000]).value_counts().sort_index())

Length stats:
 count    1.245310e+06
mean     4.891282e+01
std      4.898512e+01
min      0.000000e+00
25%      1.800000e+01
50%      3.300000e+01
75%      6.600000e+01
max      2.910000e+02
Name: payment_hist_string, dtype: float64

% length divisible by 3: 1.0

Lengths NOT divisible by 3 (sample):
[]

Empty strings: 29003
'nan' strings: 0

MONTHS OF HISTORY PER ACCOUNT:
 count    1.245310e+06
mean     1.630427e+01
std      1.632837e+01
min      0.000000e+00
25%      6.000000e+00
50%      1.100000e+01
75%      2.200000e+01
max      9.700000e+01
Name: payment_hist_string, dtype: float64

Sample payment histories:
'000000000000000000000000000'
'000000000000000000000000000000000000000000000000000000000000000000000000000000000'
'000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
'000000000000000000000000'
'000000000'
'000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
'000000000000000000000000'
'000000000000000000000000000000'
'000000000000000000000000000'
'008000000000000000000000000000'

Monthly DPD value distribution (sampled):
count    325970.000000
mean          2.328435
std          28.349612
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max         999.000000
dtype: float64

% months with DPD>0: 0.017590575819860725
Max DPD seen: 999
Value counts of top DPD buckets:
(-1, 0]         320236
(0, 29]           1646
(29, 59]           994
(59, 89]           646
(89, 119]          470
(119, 10000]      1978
Name: count, dtype: int64

In [22]:
sample_vals = []
for s in acc_train['payment_hist_string'].sample(50000, random_state=1):
    s = str(s)
    if len(s) >= 3:
        sample_vals.extend(int(s[i:i+3]) for i in range(0, len(s)-len(s)%3, 3))
sv = pd.Series(sample_vals)

# What high/sentinel values exist above normal DPD range?
print("Values >= 120:\n", sv[sv >= 120].value_counts().sort_index())
print("\nUnique values >= 900:", sorted(sv[sv >= 900].unique()))
print("Count of exactly 999:", (sv == 999).sum())

Values >= 120:
 120    30
121    24
122    23
123    34
124    37
       ..
971     1
983     1
986     1
989     1
999    20
Name: count, Length: 616, dtype: int64

Unique values >= 900: [np.int64(903), np.int64(904), np.int64(909), np.int64(918), np.int64(933), np.int64(934), np.int64(939), np.int64(948), np.int64(964), np.int64(969), np.int64(971), np.int64(983), np.int64(986), np.int64(989), np.int64(999)]
Count of exactly 999: 20

In [23]:
enq = enq_train.copy()
enq['enquiry_date'] = pd.to_datetime(enq['enquiry_date'], errors='coerce')
enq['enquiry_amt']  = pd.to_numeric(enq['enquiry_amt'], errors='coerce')

# 4a. Missing values
print("MISSING %:\n", enq.isna().mean().round(4))

# 4b. Enquiries per applicant
print("\nENQUIRIES PER APPLICANT:\n", enq.groupby('uid').size().describe())

# 4c. enquiry_type cardinality
print("\nENQUIRY TYPES:\n", enq['enquiry_type'].value_counts())

# 4d. enquiry_amt distribution (skew check)
print("\nENQUIRY AMT:\n", enq['enquiry_amt'].describe())
print("Zero-amount enquiries:", (enq['enquiry_amt']==0).sum())

# 4e. Date range — CONFIRM the 2021-01-01 reference anchor
print("\nENQUIRY DATE range:", enq['enquiry_date'].min(), "→", enq['enquiry_date'].max())

# 4f. Recency — days between enquiries (velocity signal)
#     how spread out are enquiries per person?
span = enq.groupby('uid')['enquiry_date'].agg(['min','max'])
span['span_days'] = (span['max'] - span['min']).dt.days
print("\nENQUIRY TIME SPAN PER APPLICANT (days):\n", span['span_days'].describe())

MISSING %:
 enquiry_type    0.0
enquiry_amt     0.0
enquiry_date    0.0
uid             0.0
dtype: float64

ENQUIRIES PER APPLICANT:
 count    261383.000000
mean          7.307002
std           6.997030
min           1.000000
25%           2.000000
50%           5.000000
75%          10.000000
max          69.000000
dtype: float64

ENQUIRY TYPES:
 enquiry_type
Cash loans                                      303108
Revolving loans                                 120181
Mobile operator loan                             99479
Real estate loan                                 99328
Microloan                                        99324
Unknown type of loan                             99280
Loan for purchase of shares (margin lending)     99230
Mortgage                                         99216
Credit card                                      99208
Another type of loan                             99154
Loan for the purchase of equipment               99152
Interbank credit                                 99063
Car loan                                         98994
Loan for business development                    98900
Cash loan (non-earmarked)                        98831
Loan for working capital replenishment           98814
Consumer credit                                  98664
Name: count, dtype: int64

ENQUIRY AMT:
 count    1.909926e+06
mean     1.160423e+05
std      8.207031e+04
min      1.007000e+03
25%      5.600000e+04
50%      1.080000e+05
75%      1.590000e+05
max      4.999950e+05
Name: enquiry_amt, dtype: float64
Zero-amount enquiries: 0

ENQUIRY DATE range: 2015-08-30 00:00:00 → 2021-01-01 00:00:00

ENQUIRY TIME SPAN PER APPLICANT (days):
 count    261383.000000
mean        507.757968
std         389.837746
min           0.000000
25%         108.000000
50%         523.000000
75%         802.000000
max        1905.000000
Name: span_days, dtype: float64

In [30]:
import json
import numpy as np
import pandas as pd

REF_DATE = pd.Timestamp('2021-01-01')   # confirmed snapshot/application date

def load_nested_json(path):
    with open(path) as f:
        raw = json.load(f)
    records = [rec for applicant in raw for rec in applicant if rec is not None]
    return pd.DataFrame(records)
    
    # credit types worth keeping separate; rest → 'Other'
KEEP_CREDIT_TYPES = ['Consumer credit', 'Credit card', 'Car loan', 'Mortgage', 'Microloan']

def build_account_features(acc):
    acc = acc.copy()

    # --- dtypes ---
    acc['open_date']      = pd.to_datetime(acc['open_date'], errors='coerce')
    acc['closed_date']    = pd.to_datetime(acc['closed_date'], errors='coerce')
    acc['loan_amount']    = pd.to_numeric(acc['loan_amount'], errors='coerce')
    acc['amount_overdue'] = pd.to_numeric(acc['amount_overdue'], errors='coerce')

    # --- fix garbage closed_dates (closed < open → invalid) ---
    bad = acc['closed_date'] < acc['open_date']
    acc.loc[bad, 'closed_date'] = pd.NaT

    # --- derived per-row fields ---
    acc['is_open']       = acc['closed_date'].isna().astype(int)
    acc['is_zero_amt']   = (acc['loan_amount'] == 0).astype(int)
    acc['has_overdue']   = (acc['amount_overdue'] > 0).astype(int)
    acc['days_since_open']  = (REF_DATE - acc['open_date']).dt.days
    acc['days_since_close'] = (REF_DATE - acc['closed_date']).dt.days   # NaN if open
    acc['log_loan_amount']  = np.log1p(acc['loan_amount'].clip(lower=0))

    # --- grouped credit type (rare → 'Other') ---
    acc['credit_grp'] = np.where(acc['credit_type'].isin(KEEP_CREDIT_TYPES),
                                 acc['credit_type'], 'Other')

    g = acc.groupby('uid')

    # ---- NUMERICAL aggregations ----
    num = g.agg(
        acc_n_accounts       = ('uid', 'size'),
        acc_n_open           = ('is_open', 'sum'),
        acc_n_zero_amt       = ('is_zero_amt', 'sum'),

        acc_loan_amt_sum     = ('loan_amount', 'sum'),
        acc_loan_amt_mean    = ('loan_amount', 'mean'),
        acc_loan_amt_max     = ('loan_amount', 'max'),
        acc_loan_amt_std     = ('loan_amount', 'std'),
        acc_log_loan_sum     = ('log_loan_amount', 'sum'),
        acc_log_loan_mean    = ('log_loan_amount', 'mean'),

        acc_overdue_sum      = ('amount_overdue', 'sum'),
        acc_overdue_max      = ('amount_overdue', 'max'),
        acc_n_with_overdue   = ('has_overdue', 'sum'),

        acc_n_credit_types   = ('credit_type', 'nunique'),

        # recency (anchored to REF_DATE)
        acc_days_since_open_min  = ('days_since_open', 'min'),   # most recent open
        acc_days_since_open_max  = ('days_since_open', 'max'),   # oldest open
        acc_days_since_open_mean = ('days_since_open', 'mean'),
        acc_days_since_close_min = ('days_since_close', 'min'),  # most recent close
    )

    # ---- ratio features ----
    num['acc_open_ratio']       = num['acc_n_open']        / num['acc_n_accounts']
    num['acc_overdue_ratio']    = num['acc_n_with_overdue']/ num['acc_n_accounts']
    num['acc_overdue_amt_ratio']= num['acc_overdue_sum']   / (num['acc_loan_amt_sum'] + 1)
    num['acc_zero_amt_ratio']   = num['acc_n_zero_amt']    / num['acc_n_accounts']

    # ---- CATEGORICAL: count of accounts per credit-type group ----
    cat = (acc.groupby(['uid', 'credit_grp']).size()
              .unstack(fill_value=0)
              .add_prefix('acc_cnt_'))
    # normalized share per type
    cat_share = cat.div(cat.sum(axis=1), axis=0).add_suffix('_share')

    out = num.join(cat).join(cat_share)
    return out.reset_index()
    
def _parse_ph(s):
    """Return list of monthly DPD ints; most recent is last."""
    s = str(s)
    if s in ('', 'nan') or len(s) < 3:
        return []
    n = len(s) - (len(s) % 3)
    return [int(s[i:i+3]) for i in range(0, n, 3)]

def _ph_row_features(s):
    vals = _parse_ph(s)
    if not vals:
        return dict(ph_n_months=0, ph_max_dpd=0, ph_mean_dpd=0, ph_sum_dpd=0,
                    ph_n_late=0, ph_n_30=0, ph_n_90=0, ph_n_180=0, ph_n_360=0,
                    ph_recent_dpd=0, ph_recent3_max=0, ph_late_ratio=0,
                    ph_has_history=0)
    arr = np.array(vals)
    return dict(
        ph_n_months   = len(arr),
        ph_max_dpd    = int(arr.max()),
        ph_mean_dpd   = float(arr.mean()),
        ph_sum_dpd    = int(arr.sum()),
        ph_n_late     = int((arr > 0).sum()),
        ph_n_30       = int((arr >= 30).sum()),
        ph_n_90       = int((arr >= 90).sum()),
        ph_n_180      = int((arr >= 180).sum()),
        ph_n_360      = int((arr >= 360).sum()),
        ph_recent_dpd = int(arr[-1]),                 # most recent month
        ph_recent3_max= int(arr[-3:].max()),          # worst in last 3 months
        ph_late_ratio = float((arr > 0).mean()),
        ph_has_history= 1,
    )

def build_payment_features(acc):
    acc = acc.copy()
    # per-account payment features
    ph = acc['payment_hist_string'].apply(_ph_row_features).apply(pd.Series)
    ph['uid'] = acc['uid'].values

    g = ph.groupby('uid')
    out = g.agg(
        # worst-ever across all accounts
        pmt_max_dpd       = ('ph_max_dpd', 'max'),
        pmt_mean_dpd      = ('ph_mean_dpd', 'mean'),
        pmt_sum_dpd       = ('ph_sum_dpd', 'sum'),

        # delinquency counts summed across accounts
        pmt_n_late        = ('ph_n_late', 'sum'),
        pmt_n_30          = ('ph_n_30', 'sum'),
        pmt_n_90          = ('ph_n_90', 'sum'),
        pmt_n_180         = ('ph_n_180', 'sum'),
        pmt_n_360         = ('ph_n_360', 'sum'),

        # recent behaviour (max across accounts = worst recent)
        pmt_recent_dpd_max= ('ph_recent_dpd', 'max'),
        pmt_recent3_max   = ('ph_recent3_max', 'max'),

        # history coverage
        pmt_total_months  = ('ph_n_months', 'sum'),
        pmt_late_ratio_max= ('ph_late_ratio', 'max'),
        pmt_late_ratio_mean=('ph_late_ratio', 'mean'),
        pmt_n_acc_with_hist=('ph_has_history', 'sum'),
    )

    # any severe delinquency flags (very high signal, low prevalence)
    out['pmt_ever_90plus']  = (out['pmt_n_90']  > 0).astype(int)
    out['pmt_ever_180plus'] = (out['pmt_n_180'] > 0).astype(int)
    out['pmt_ever_360plus'] = (out['pmt_n_360'] > 0).astype(int)

    return out.reset_index()
    
    # only these enquiry types looked "real"; rest is likely synthetic noise
KEEP_ENQ_TYPES = ['Cash loans', 'Revolving loans']

def build_enquiry_features(enq):
    enq = enq.copy()
    enq['enquiry_date'] = pd.to_datetime(enq['enquiry_date'], errors='coerce')
    enq['enquiry_amt']  = pd.to_numeric(enq['enquiry_amt'], errors='coerce')
    enq['log_enq_amt']  = np.log1p(enq['enquiry_amt'].clip(lower=0))
    enq['days_ago']     = (REF_DATE - enq['enquiry_date']).dt.days

    # recency window flags
    for w in [30, 90, 180, 365]:
        enq[f'in_{w}d'] = (enq['days_ago'] <= w).astype(int)

    g = enq.groupby('uid')
    num = g.agg(
        enq_n              = ('uid', 'size'),
        enq_amt_sum        = ('enquiry_amt', 'sum'),
        enq_amt_mean       = ('enquiry_amt', 'mean'),
        enq_amt_max        = ('enquiry_amt', 'max'),
        enq_log_amt_sum    = ('log_enq_amt', 'sum'),
        enq_log_amt_mean   = ('log_enq_amt', 'mean'),
        enq_n_types        = ('enquiry_type', 'nunique'),

        enq_days_since_last= ('days_ago', 'min'),   # recency
        enq_days_since_first=('days_ago', 'max'),
        enq_n_30d          = ('in_30d', 'sum'),
        enq_n_90d          = ('in_90d', 'sum'),
        enq_n_180d         = ('in_180d', 'sum'),
        enq_n_365d         = ('in_365d', 'sum'),
    )
    num['enq_span_days'] = num['enq_days_since_first'] - num['enq_days_since_last']

    # CATEGORICAL: counts for the two "real" enquiry types
    enq['enq_grp'] = np.where(enq['enquiry_type'].isin(KEEP_ENQ_TYPES),
                              enq['enquiry_type'], 'Other')
    cat = (enq.groupby(['uid', 'enq_grp']).size()
              .unstack(fill_value=0)
              .add_prefix('enq_cnt_'))

    out = num.join(cat)
    return out.reset_index()
    
def build_master(flag, acc, enq):
    m = flag.copy()

    # --- flag-table feature: contract type (categorical) ---
    m['is_cash_loan'] = (m['NAME_CONTRACT_TYPE'] == 'Cash loans').astype(int)

    # --- merge aggregated features (LEFT join keeps all applicants) ---
    m = m.merge(build_account_features(acc), on='uid', how='left')
    m = m.merge(build_payment_features(acc), on='uid', how='left')
    m = m.merge(build_enquiry_features(enq), on='uid', how='left')

    # --- missingness flags BEFORE filling ---
    m['has_accounts'] = m['acc_n_accounts'].notna().astype(int)
    # (every uid has enquiries, so no has_enquiries flag needed)

    # --- fill NaNs from the LEFT join (applicants w/o accounts) ---
    acc_cols = [c for c in m.columns if c.startswith(('acc_', 'pmt_'))]
    m[acc_cols] = m[acc_cols].fillna(0)

    # enquiry cols should have no NaN (100% coverage) but be safe
    enq_cols = [c for c in m.columns if c.startswith('enq_')]
    m[enq_cols] = m[enq_cols].fillna(0)

    # std can be NaN when a group has 1 account → fill 0
    m = m.fillna(0)

    return m
    
# TRAIN
flag_train = pd.read_csv(r'E:\senior_ds_test\senior_ds_test\data\train\train_flag.csv')
acc_train  = load_nested_json(r'E:\senior_ds_test\senior_ds_test\data\train\accounts_data_train.json')
enq_train  = load_nested_json(r'E:\senior_ds_test\senior_ds_test\data\train\enquiry_data_train.json')
train = build_master(flag_train, acc_train, enq_train)

# TEST
flag_test  = pd.read_csv(r'E:\senior_ds_test\senior_ds_test\data\test\test_flag.csv')   # or sample_submission
acc_test   = load_nested_json(r'E:\senior_ds_test\senior_ds_test\data\test\accounts_data_test.json')
enq_test   = load_nested_json(r'E:\senior_ds_test\senior_ds_test\data\test\enquiry_data_test.json')
test  = build_master(flag_test, acc_test, enq_test)

print("Train:", train.shape)
print("Test :", test.shape)

# ---- align columns between train & test ----
# (one-hot / count columns can differ if a category appears in one set only)
feature_cols = [c for c in train.columns
                if c not in ['uid', 'TARGET', 'NAME_CONTRACT_TYPE']]

# add missing cols to test (fill 0), drop extras
for c in feature_cols:
    if c not in test.columns:
        test[c] = 0

# ensure test only carries the same feature set, in the same order
test = test[['uid'] + feature_cols]

print("\nFinal feature count:", len(feature_cols))
print("Any NaN in train features?", train[feature_cols].isna().any().any())
print("Any NaN in test features? ", test[feature_cols].isna().any().any())


# ---- 6a. shape & no leakage columns ----
assert 'TARGET' not in feature_cols
assert train['uid'].is_unique
assert test['uid'].is_unique

# ---- 6b. do our "strong" payment features separate the classes? ----
check_cols = [
    'pmt_max_dpd', 'pmt_n_90', 'pmt_n_360', 'pmt_ever_90plus',
    'acc_n_with_overdue', 'acc_open_ratio', 'acc_n_accounts',
    'enq_n', 'enq_n_90d', 'enq_days_since_last', 'is_cash_loan',
    'has_accounts'
]
print(train.groupby('TARGET')[check_cols].mean().T)

corr = train[feature_cols + ['TARGET']].corr()['TARGET'].drop('TARGET')
print("TOP + correlated with default:\n", corr.sort_values(ascending=False).head(15))
print("\nTOP - correlated with default:\n", corr.sort_values().head(10))

train.to_csv('features_train.csv', index=False)
test.to_csv('features_test.csv', index=False)
print("Saved engineered features as CSV.")
print("Saved engineered features.")

Train: (261383, 72)
Test : (46127, 71)

Final feature count: 69
Any NaN in train features? False
Any NaN in test features?  False
TARGET                        0           1
pmt_max_dpd           29.938950   26.672508
pmt_n_90               0.562765    0.495037
pmt_n_360              0.133028    0.124757
pmt_ever_90plus        0.096644    0.084010
acc_n_with_overdue     0.010477    0.027212
acc_open_ratio         0.350902    0.407600
acc_n_accounts         4.775963    4.631334
enq_n                  7.303047    7.352139
enq_n_90d              1.703902    1.464691
enq_days_since_last  114.046657  134.840956
is_cash_loan           0.902204    0.935603
has_accounts           0.859919    0.819537
TOP + correlated with default:
 enq_days_since_first         0.071712
acc_open_ratio               0.048146
enq_span_days                0.047705
acc_n_open                   0.044663
acc_cnt_Microloan_share      0.039542
acc_n_with_overdue           0.037761
enq_days_since_last          0.032345
is_cash_loan                 0.030986
acc_cnt_Microloan            0.029550
acc_overdue_ratio            0.027708
acc_cnt_Credit card          0.021046
acc_cnt_Credit card_share    0.017972
acc_overdue_sum              0.011849
acc_overdue_max              0.009177
pmt_recent_dpd_max           0.006787
Name: TARGET, dtype: float64

TOP - correlated with default:
 acc_days_since_open_mean        -0.083627
acc_days_since_open_max         -0.072554
acc_days_since_open_min         -0.052801
acc_cnt_Consumer credit_share   -0.038129
acc_days_since_close_min        -0.037063
acc_log_loan_mean               -0.034991
enq_n_90d                       -0.032971
enq_n_180d                      -0.031924
has_accounts                    -0.031364
pmt_total_months                -0.029370
Name: TARGET, dtype: float64
Saved engineered features as CSV.
Saved engineered features.

In [27]:
# 1. Does the account aggregation itself produce data?
acc_feats = build_account_features(acc_train)
print("acc_feats shape:", acc_feats.shape)          # expect ~223918 rows
print(acc_feats[['uid','acc_n_accounts']].head())
print("acc_n_accounts mean:", acc_feats['acc_n_accounts'].mean())  # expect ~5.6

# 2. Do the uids actually match?
print("\nflag uid sample:", flag_train['uid'].head(3).tolist())
print("acc  uid sample:", acc_feats['uid'].head(3).tolist())
print("flag uid dtype:", flag_train['uid'].dtype)
print("acc  uid dtype:", acc_feats['uid'].dtype)

# 3. Overlap after aggregation
print("\noverlap:", flag_train['uid'].isin(acc_feats['uid']).mean())  # expect 0.857

# 4. Check for hidden whitespace
print("flag uid has spaces:", flag_train['uid'].str.contains(' ').any())
print("acc  uid has spaces:", acc_feats['uid'].str.contains(' ').any())

acc_feats shape: (39572, 34)
           uid  acc_n_accounts
0  AAA14437029              12
1  AAB12915377               3
2  AAB55088883               6
3  AAB68152393               7
4  AAC29580834               5
acc_n_accounts mean: 5.5598150207217225

flag uid sample: ['XDA69787158', 'BSE47789733', 'NTJ92213825']
acc  uid sample: ['AAA14437029', 'AAB12915377', 'AAB55088883']
flag uid dtype: object
acc  uid dtype: object

overlap: 0.0
flag uid has spaces: False
acc  uid has spaces: False

In [29]:
import json, numpy as np, pandas as pd

def load_nested_json(path):
    with open(path) as f:
        raw = json.load(f)
    records = [rec for applicant in raw for rec in applicant if rec is not None]
    return pd.DataFrame(records)

# ---- RELOAD everything fresh ----
flag_train = pd.read_csv(r'E:\senior_ds_test\senior_ds_test\data\train\train_flag.csv')
acc_train  = load_nested_json(r'E:\senior_ds_test\senior_ds_test\data\train\accounts_data_train.json')
enq_train  = load_nested_json(r'E:\senior_ds_test\senior_ds_test\data\train\enquiry_data_train.json')

# ---- VERIFY the flatten worked (these MUST pass) ----
print("acc_train rows:", len(acc_train))          # expect 1,245,310
print("acc_train uids:", acc_train['uid'].nunique())  # expect 223,918
print("flag rows:", len(flag_train))              # expect 261,383

assert len(acc_train) == 1_245_310, "accounts not flattened correctly!"
assert acc_train['uid'].nunique() == 223_918, "wrong uid count!"

# ---- VERIFY overlap on RAW data ----
overlap = flag_train['uid'].isin(acc_train['uid']).mean()
print("raw overlap (flag∩acc):", overlap)         # expect ~0.857
assert overlap > 0.8, "uid mismatch — check load order!"

train = build_master(flag_train, acc_train, enq_train)

# ---- CRITICAL re-check: account features must now be non-zero ----
print(train[['acc_n_accounts','has_accounts','pmt_max_dpd']].describe())
print("\nhas_accounts mean:", train['has_accounts'].mean())  # expect ~0.857

check_cols = ['pmt_max_dpd','pmt_n_90','pmt_ever_90plus','acc_n_with_overdue',
              'acc_open_ratio','acc_n_accounts','acc_overdue_ratio',
              'enq_n','is_cash_loan','has_accounts']
print(train.groupby('TARGET')[check_cols].mean().T)

acc_train rows: 1245310
acc_train uids: 223918
flag rows: 261383
raw overlap (flag∩acc): 0.8566662713336368
       acc_n_accounts   has_accounts    pmt_max_dpd
count   261383.000000  261383.000000  261383.000000
mean         4.764311       0.856666      29.675805
std          4.501590       0.350414      90.731255
min          0.000000       0.000000       0.000000
25%          1.000000       1.000000       0.000000
50%          4.000000       1.000000       0.000000
75%          7.000000       1.000000      13.000000
max        116.000000       1.000000     999.000000

has_accounts mean: 0.8566662713336368
TARGET                      0          1
pmt_max_dpd         29.938950  26.672508
pmt_n_90             0.562765   0.495037
pmt_ever_90plus      0.096644   0.084010
acc_n_with_overdue   0.010477   0.027212
acc_open_ratio       0.350902   0.407600
acc_n_accounts       4.775963   4.631334
acc_overdue_ratio    0.002235   0.005531
enq_n                7.303047   7.352139
is_cash_loan         0.902204   0.935603
has_accounts         0.859919   0.819537

In [31]:
# 1. Confirm no accidental leakage / weirdness in top features
print(train[['enq_days_since_first','acc_days_since_open_mean',
             'acc_open_ratio','acc_overdue_ratio']].describe())

# 2. Test set has 71 cols vs train 72 — that's fine (train has TARGET).
#    But confirm feature_cols align perfectly:
print("train features:", len([c for c in train.columns if c not in ['uid','TARGET','NAME_CONTRACT_TYPE']]))
print("test features :", len([c for c in test.columns if c not in ['uid','NAME_CONTRACT_TYPE']]))
print("match:", set(feature_cols) == set(c for c in test.columns if c!='uid'))

       enq_days_since_first  acc_days_since_open_mean  acc_open_ratio  \
count         261383.000000             261383.000000   261383.000000
mean             623.479813                927.625207        0.355469
std              338.251878                644.848893        0.320503
min                0.000000                  0.000000        0.000000
25%              365.000000                423.000000        0.000000
50%              621.000000                927.000000        0.333333
75%              862.000000               1361.594118        0.500000
max             1951.000000               2922.000000        1.000000

       acc_overdue_ratio
count      261383.000000
mean            0.002500
std             0.032379
min             0.000000
25%             0.000000
50%             0.000000
75%             0.000000
max             1.000000
train features: 69
test features : 69
match: True

In [32]:

from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier
import numpy as np

X = train[feature_cols]
y = train['TARGET']

spw = (y == 0).sum() / (y == 1).sum()
print("scale_pos_weight:", round(spw, 2))

model = XGBClassifier(
    n_estimators=400, max_depth=4, learning_rate=0.05,
    subsample=0.8, colsample_bytree=0.8,
    scale_pos_weight=spw, eval_metric='auc',
    n_jobs=-1, random_state=42,
)

# ---- Cross-validated AUC (more reliable than single split) ----
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
oof = cross_val_predict(model, X, y, cv=cv, method='predict_proba', n_jobs=-1)[:, 1]
cv_auc = roc_auc_score(y, oof)
print(f"\n📊 BASELINE 5-FOLD CV AUC: {cv_auc:.5f}")

# ---- Fit on full data for feature importance ----
model.fit(X, y)
imp = pd.Series(model.feature_importances_, index=feature_cols).sort_values(ascending=False)
print("\nTOP 20 FEATURES:\n", imp.head(20))

scale_pos_weight: 11.41

📊 BASELINE 5-FOLD CV AUC: 0.67718

TOP 20 FEATURES:
 acc_days_since_open_mean    0.075839
enq_days_since_first        0.053374
is_cash_loan                0.051230
acc_n_open                  0.050572
enq_n_180d                  0.036038
enq_n_90d                   0.034823
acc_cnt_Microloan_share     0.034717
acc_open_ratio              0.031835
acc_days_since_open_min     0.028335
acc_overdue_sum             0.022503
acc_overdue_max             0.020916
pmt_recent_dpd_max          0.019506
acc_cnt_Microloan           0.018188
acc_loan_amt_mean           0.016833
enq_span_days               0.016749
enq_n_365d                  0.016532
enq_log_amt_sum             0.016453
acc_days_since_open_max     0.015665
acc_overdue_amt_ratio       0.015008
enq_days_since_last         0.014613
dtype: float32

In [33]:
def add_interaction_features(df):
    df = df.copy()
    eps = 1e-6
    # credit-hunger: recent enquiries relative to total history
    df['enq_recent_ratio']    = df['enq_n_90d'] / (df['enq_n'] + eps)
    df['enq_velocity']        = df['enq_n'] / (df['enq_span_days'] + 30)
    # burden: open loans vs total, amount per account
    df['open_x_amount']       = df['acc_open_ratio'] * df['acc_log_loan_mean']
    df['amt_per_account']     = df['acc_log_loan_sum'] / (df['acc_n_accounts'] + eps)
    # tenure gap: how long since most recent vs oldest account
    df['acc_tenure_gap']      = df['acc_days_since_open_max'] - df['acc_days_since_open_min']
    # enquiry vs account activity mismatch (applying a lot but few accounts = risk)
    df['enq_to_acc_ratio']    = df['enq_n'] / (df['acc_n_accounts'] + 1)
    # recency combo
    df['recency_combo']       = df['acc_days_since_open_mean'] + df['enq_days_since_first']
    # microloan risk amplified by open ratio
    df['microloan_x_open']    = df['acc_cnt_Microloan_share'] * df['acc_open_ratio']
    return df

train = add_interaction_features(train)
test  = add_interaction_features(test)

feature_cols = [c for c in train.columns
                if c not in ['uid','TARGET','NAME_CONTRACT_TYPE']]
# align test again
for c in feature_cols:
    if c not in test.columns: test[c] = 0
test = test[['uid'] + feature_cols]

print("New feature count:", len(feature_cols))

X = train[feature_cols]; y = train['TARGET']
oof = cross_val_predict(model, X, y, cv=cv, method='predict_proba', n_jobs=-1)[:,1]
print("CV AUC with interactions:", round(roc_auc_score(y, oof), 5))

New feature count: 77
CV AUC with interactions: 0.6768

In [34]:
# reload clean features (no interactions)
train = pd.read_csv('features_train.csv')
test  = pd.read_csv('features_test.csv')

feature_cols = [c for c in train.columns
                if c not in ['uid','TARGET','NAME_CONTRACT_TYPE']]
for c in feature_cols:
    if c not in test.columns: test[c] = 0
test = test[['uid'] + feature_cols]

print("Back to baseline features:", len(feature_cols))

Back to baseline features: 69

In [36]:
import optuna
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier

X = train[feature_cols]
y = train['TARGET']
spw = (y == 0).sum() / (y == 1).sum()
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

def objective(trial):
    params = dict(
        n_estimators     = trial.suggest_int('n_estimators', 300, 900),
        max_depth        = trial.suggest_int('max_depth', 3, 6),
        learning_rate    = trial.suggest_float('learning_rate', 0.01, 0.1, log=True),
        subsample        = trial.suggest_float('subsample', 0.6, 1.0),
        colsample_bytree = trial.suggest_float('colsample_bytree', 0.5, 1.0),
        min_child_weight = trial.suggest_int('min_child_weight', 1, 20),   # ↑ = more reg
        gamma            = trial.suggest_float('gamma', 0, 5),             # min split gain
        reg_alpha        = trial.suggest_float('reg_alpha', 0, 5),         # L1
        reg_lambda       = trial.suggest_float('reg_lambda', 0, 10),       # L2
        scale_pos_weight = spw,
        eval_metric      = 'auc',
        n_jobs           = -1,
        random_state     = 42,
    )
    model = XGBClassifier(**params)
    oof = cross_val_predict(model, X, y, cv=cv, method='predict_proba', n_jobs=-1)[:, 1]
    return roc_auc_score(y, oof)

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=40, show_progress_bar=True)

print("\n📊 BEST CV AUC:", round(study.best_value, 5))
print("BEST PARAMS:", study.best_params)

e:\senior_ds_test\senior_ds_test\venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2026-09-13 22:39:33,601] A new study created in memory with name: no-name-8e8b4f91-63fd-4b35-898f-9793340b1b16
Best trial: 0. Best value: 0.677904:   2%|▎         | 1/40 [00:52<34:16, 52.73s/it]

[I 2026-09-13 22:40:26,807] Trial 0 finished with value: 0.6779042062394383 and parameters: {'n_estimators': 781, 'max_depth': 3, 'learning_rate': 0.061994452155343195, 'subsample': 0.9600799929161047, 'colsample_bytree': 0.6991088200860698, 'min_child_weight': 18, 'gamma': 3.440761662122055, 'reg_alpha': 2.179135497645931, 'reg_lambda': 9.809945860987352}. Best is trial 0 with value: 0.6779042062394383.

Best trial: 0. Best value: 0.677904:   5%|▌         | 2/40 [02:12<43:33, 68.79s/it]

[I 2026-09-13 22:41:46,951] Trial 1 finished with value: 0.6763210300871134 and parameters: {'n_estimators': 853, 'max_depth': 5, 'learning_rate': 0.02703734785091391, 'subsample': 0.8088868991143434, 'colsample_bytree': 0.9983296519867224, 'min_child_weight': 18, 'gamma': 4.521811411536387, 'reg_alpha': 4.7538726301147465, 'reg_lambda': 3.4633946352081155}. Best is trial 0 with value: 0.6779042062394383.

Best trial: 0. Best value: 0.677904:   8%|▊         | 3/40 [03:16<40:54, 66.34s/it]

[I 2026-09-13 22:42:50,377] Trial 2 finished with value: 0.6747153212808116 and parameters: {'n_estimators': 730, 'max_depth': 4, 'learning_rate': 0.06872007646359697, 'subsample': 0.7760440886992864, 'colsample_bytree': 0.799019820568401, 'min_child_weight': 7, 'gamma': 4.8060678608547125, 'reg_alpha': 3.8714933907346345, 'reg_lambda': 9.618656812977665}. Best is trial 0 with value: 0.6779042062394383.

Best trial: 0. Best value: 0.677904:  10%|█         | 4/40 [04:16<38:27, 64.10s/it]

[I 2026-09-13 22:43:51,045] Trial 3 finished with value: 0.6756689680517866 and parameters: {'n_estimators': 794, 'max_depth': 4, 'learning_rate': 0.05293202788054951, 'subsample': 0.7681651529133856, 'colsample_bytree': 0.7259626702197239, 'min_child_weight': 16, 'gamma': 1.9839949364943688, 'reg_alpha': 3.5015980676987453, 'reg_lambda': 4.762496038892224}. Best is trial 0 with value: 0.6779042062394383.

Best trial: 0. Best value: 0.677904:  12%|█▎        | 5/40 [04:45<29:56, 51.33s/it]

[I 2026-09-13 22:44:19,749] Trial 4 finished with value: 0.6655205899142498 and parameters: {'n_estimators': 327, 'max_depth': 3, 'learning_rate': 0.011305894076619062, 'subsample': 0.6347784454138469, 'colsample_bytree': 0.6152515932283626, 'min_child_weight': 20, 'gamma': 2.2881712432002432, 'reg_alpha': 3.422287912778879, 'reg_lambda': 3.44839349752051}. Best is trial 0 with value: 0.6779042062394383.

Best trial: 0. Best value: 0.677904:  15%|█▌        | 6/40 [05:38<29:28, 52.01s/it]

[I 2026-09-13 22:45:13,067] Trial 5 finished with value: 0.6694278906364549 and parameters: {'n_estimators': 658, 'max_depth': 5, 'learning_rate': 0.07456168420383244, 'subsample': 0.8665532581750021, 'colsample_bytree': 0.6545862244314342, 'min_child_weight': 11, 'gamma': 3.259941896124823, 'reg_alpha': 0.8929738964636719, 'reg_lambda': 6.241538099263769}. Best is trial 0 with value: 0.6779042062394383.

Best trial: 6. Best value: 0.678507:  18%|█▊        | 7/40 [06:22<27:11, 49.43s/it]

[I 2026-09-13 22:45:57,184] Trial 6 finished with value: 0.6785069708136008 and parameters: {'n_estimators': 603, 'max_depth': 3, 'learning_rate': 0.05345525569569436, 'subsample': 0.8550712420322422, 'colsample_bytree': 0.5072322365513191, 'min_child_weight': 1, 'gamma': 2.428019687844923, 'reg_alpha': 3.217674615644892, 'reg_lambda': 2.473370971363169}. Best is trial 6 with value: 0.6785069708136008.

Best trial: 6. Best value: 0.678507:  20%|██        | 8/40 [07:06<25:25, 47.67s/it]

[I 2026-09-13 22:46:41,091] Trial 7 finished with value: 0.6784751093217422 and parameters: {'n_estimators': 559, 'max_depth': 3, 'learning_rate': 0.062499373975730445, 'subsample': 0.6111393768217186, 'colsample_bytree': 0.9405874070367686, 'min_child_weight': 6, 'gamma': 2.6814310639430197, 'reg_alpha': 3.997406213895374, 'reg_lambda': 6.872603841163536}. Best is trial 6 with value: 0.6785069708136008.

Best trial: 6. Best value: 0.678507:  22%|██▎       | 9/40 [08:17<28:18, 54.79s/it]

[I 2026-09-13 22:47:51,531] Trial 8 finished with value: 0.6768357926700309 and parameters: {'n_estimators': 711, 'max_depth': 6, 'learning_rate': 0.01301635633133572, 'subsample': 0.6877389275292931, 'colsample_bytree': 0.5379750349194798, 'min_child_weight': 11, 'gamma': 4.040593496949835, 'reg_alpha': 3.679353929935349, 'reg_lambda': 2.6649867394108764}. Best is trial 6 with value: 0.6785069708136008.

Best trial: 6. Best value: 0.678507:  25%|██▌       | 10/40 [08:59<25:23, 50.77s/it]

[I 2026-09-13 22:48:33,306] Trial 9 finished with value: 0.6754884562540546 and parameters: {'n_estimators': 581, 'max_depth': 3, 'learning_rate': 0.02127296485107994, 'subsample': 0.9112343225181709, 'colsample_bytree': 0.7292547689604766, 'min_child_weight': 13, 'gamma': 1.867880579969572, 'reg_alpha': 3.6979529896854775, 'reg_lambda': 5.027860975628833}. Best is trial 6 with value: 0.6785069708136008.

Best trial: 6. Best value: 0.678507:  28%|██▊       | 11/40 [10:00<26:03, 53.93s/it]

[I 2026-09-13 22:49:34,388] Trial 10 finished with value: 0.6713004693375113 and parameters: {'n_estimators': 770, 'max_depth': 4, 'learning_rate': 0.08275534882810207, 'subsample': 0.7757905461101633, 'colsample_bytree': 0.8069886605478944, 'min_child_weight': 2, 'gamma': 2.46191393279818, 'reg_alpha': 2.879957948897493, 'reg_lambda': 0.36119568163142546}. Best is trial 6 with value: 0.6785069708136008.

Best trial: 11. Best value: 0.678713:  30%|███       | 12/40 [10:36<22:41, 48.63s/it]

[I 2026-09-13 22:50:10,906] Trial 11 finished with value: 0.6787125086728463 and parameters: {'n_estimators': 503, 'max_depth': 3, 'learning_rate': 0.06444892840427893, 'subsample': 0.8029082564234086, 'colsample_bytree': 0.746196626828868, 'min_child_weight': 2, 'gamma': 3.4503810316925057, 'reg_alpha': 4.828877177638869, 'reg_lambda': 6.61637407261071}. Best is trial 11 with value: 0.6787125086728463.

Best trial: 11. Best value: 0.678713:  32%|███▎      | 13/40 [11:18<20:57, 46.57s/it]

[I 2026-09-13 22:50:52,732] Trial 12 finished with value: 0.6784266877544525 and parameters: {'n_estimators': 595, 'max_depth': 3, 'learning_rate': 0.051974499012010865, 'subsample': 0.8161203714289875, 'colsample_bytree': 0.5859694579457231, 'min_child_weight': 1, 'gamma': 2.241551253635087, 'reg_alpha': 3.0966162837270623, 'reg_lambda': 1.1948938201787207}. Best is trial 11 with value: 0.6787125086728463.

Best trial: 11. Best value: 0.678713:  35%|███▌      | 14/40 [11:57<19:12, 44.33s/it]

[I 2026-09-13 22:51:31,878] Trial 13 finished with value: 0.678507542392401 and parameters: {'n_estimators': 550, 'max_depth': 3, 'learning_rate': 0.04160076123612211, 'subsample': 0.857680417674769, 'colsample_bytree': 0.7184456313525045, 'min_child_weight': 2, 'gamma': 3.1043285244434817, 'reg_alpha': 4.637589755886621, 'reg_lambda': 4.024981416331757}. Best is trial 11 with value: 0.6787125086728463.

Best trial: 11. Best value: 0.678713:  38%|███▊      | 15/40 [12:34<17:33, 42.15s/it]

[I 2026-09-13 22:52:08,985] Trial 14 finished with value: 0.6783220145337314 and parameters: {'n_estimators': 514, 'max_depth': 3, 'learning_rate': 0.053266848129672875, 'subsample': 0.9109574634505251, 'colsample_bytree': 0.8586095487285383, 'min_child_weight': 2, 'gamma': 3.570917206072116, 'reg_alpha': 4.426413978852735, 'reg_lambda': 2.842631189767142}. Best is trial 11 with value: 0.6787125086728463.

Best trial: 11. Best value: 0.678713:  40%|████      | 16/40 [13:03<15:18, 38.25s/it]

[I 2026-09-13 22:52:38,181] Trial 15 finished with value: 0.6784660804515762 and parameters: {'n_estimators': 387, 'max_depth': 3, 'learning_rate': 0.05627006713858251, 'subsample': 0.7734830719840253, 'colsample_bytree': 0.6933996967393198, 'min_child_weight': 2, 'gamma': 4.968771581449484, 'reg_alpha': 4.351880742060463, 'reg_lambda': 7.601487146456154}. Best is trial 11 with value: 0.6787125086728463.

Best trial: 11. Best value: 0.678713:  42%|████▎     | 17/40 [13:47<15:14, 39.75s/it]

[I 2026-09-13 22:53:21,409] Trial 16 finished with value: 0.6776022288583012 and parameters: {'n_estimators': 629, 'max_depth': 3, 'learning_rate': 0.07672466490770857, 'subsample': 0.8112437627595468, 'colsample_bytree': 0.7016793772647926, 'min_child_weight': 2, 'gamma': 2.9684812820898427, 'reg_alpha': 4.882577460733743, 'reg_lambda': 5.313368923946671}. Best is trial 11 with value: 0.6787125086728463.

Best trial: 11. Best value: 0.678713:  45%|████▌     | 18/40 [14:25<14:24, 39.31s/it]

[I 2026-09-13 22:53:59,708] Trial 17 finished with value: 0.6757949645704752 and parameters: {'n_estimators': 425, 'max_depth': 3, 'learning_rate': 0.029164392539038117, 'subsample': 0.8416174348452437, 'colsample_bytree': 0.81741955909304, 'min_child_weight': 3, 'gamma': 4.900099556801595, 'reg_alpha': 4.2379811922644315, 'reg_lambda': 6.102835081655654}. Best is trial 11 with value: 0.6787125086728463.

Best trial: 11. Best value: 0.678713:  48%|████▊     | 19/40 [14:58<13:08, 37.54s/it]

[I 2026-09-13 22:54:33,110] Trial 18 finished with value: 0.6783124175428912 and parameters: {'n_estimators': 441, 'max_depth': 3, 'learning_rate': 0.050554790822685776, 'subsample': 0.8519344546775447, 'colsample_bytree': 0.7419977065358017, 'min_child_weight': 6, 'gamma': 2.8340263268028645, 'reg_alpha': 4.881241125050792, 'reg_lambda': 8.282025165693137}. Best is trial 11 with value: 0.6787125086728463.

Best trial: 19. Best value: 0.678793:  50%|█████     | 20/40 [15:38<12:44, 38.22s/it]

[I 2026-09-13 22:55:12,929] Trial 19 finished with value: 0.6787925435373627 and parameters: {'n_estimators': 450, 'max_depth': 3, 'learning_rate': 0.06327229901940536, 'subsample': 0.8294458100861908, 'colsample_bytree': 0.6462744096924866, 'min_child_weight': 2, 'gamma': 2.179037064892456, 'reg_alpha': 4.229727203194724, 'reg_lambda': 8.019145148631747}. Best is trial 19 with value: 0.6787925435373627.

Best trial: 19. Best value: 0.678793:  52%|█████▎    | 21/40 [16:14<11:51, 37.47s/it]

[I 2026-09-13 22:55:48,653] Trial 20 finished with value: 0.6760319065597356 and parameters: {'n_estimators': 454, 'max_depth': 4, 'learning_rate': 0.07703176589259049, 'subsample': 0.8463379991295393, 'colsample_bytree': 0.6763493309710032, 'min_child_weight': 4, 'gamma': 3.9344864667464385, 'reg_alpha': 4.9562969729498585, 'reg_lambda': 4.792590818281678}. Best is trial 19 with value: 0.6787925435373627.

Best trial: 19. Best value: 0.678793:  55%|█████▌    | 22/40 [16:52<11:18, 37.68s/it]

[I 2026-09-13 22:56:26,828] Trial 21 finished with value: 0.6787009475653306 and parameters: {'n_estimators': 532, 'max_depth': 3, 'learning_rate': 0.06047577746547871, 'subsample': 0.765478320690484, 'colsample_bytree': 0.7407819821667285, 'min_child_weight': 7, 'gamma': 3.683073570175738, 'reg_alpha': 4.015034236265882, 'reg_lambda': 6.931543040854253}. Best is trial 19 with value: 0.6787925435373627.

Best trial: 19. Best value: 0.678793:  57%|█████▊    | 23/40 [17:29<10:38, 37.54s/it]

[I 2026-09-13 22:57:04,022] Trial 22 finished with value: 0.6780736403756475 and parameters: {'n_estimators': 506, 'max_depth': 3, 'learning_rate': 0.04434438099988533, 'subsample': 0.8481932741100698, 'colsample_bytree': 0.5110067819682684, 'min_child_weight': 4, 'gamma': 1.9853162245674092, 'reg_alpha': 4.993377677701589, 'reg_lambda': 8.305637415308055}. Best is trial 19 with value: 0.6787925435373627.

Best trial: 19. Best value: 0.678793:  60%|██████    | 24/40 [17:55<09:04, 34.02s/it]

[I 2026-09-13 22:57:29,851] Trial 23 finished with value: 0.6780658708561101 and parameters: {'n_estimators': 340, 'max_depth': 3, 'learning_rate': 0.0849408306411388, 'subsample': 0.778562864374788, 'colsample_bytree': 0.686036981395856, 'min_child_weight': 2, 'gamma': 1.893328282919813, 'reg_alpha': 4.209571725773056, 'reg_lambda': 6.100651537179505}. Best is trial 19 with value: 0.6787925435373627.

Best trial: 19. Best value: 0.678793:  62%|██████▎   | 25/40 [18:27<08:21, 33.41s/it]

[I 2026-09-13 22:58:01,828] Trial 24 finished with value: 0.6783185985970235 and parameters: {'n_estimators': 415, 'max_depth': 3, 'learning_rate': 0.05471016182669425, 'subsample': 0.7967280307385509, 'colsample_bytree': 0.5704392626545033, 'min_child_weight': 3, 'gamma': 2.8608711359370664, 'reg_alpha': 4.52045477364162, 'reg_lambda': 5.42799660788322}. Best is trial 19 with value: 0.6787925435373627.

Best trial: 19. Best value: 0.678793:  65%|██████▌   | 26/40 [19:05<08:06, 34.78s/it]

[I 2026-09-13 22:58:39,803] Trial 25 finished with value: 0.6782837667726725 and parameters: {'n_estimators': 525, 'max_depth': 3, 'learning_rate': 0.042584698817773554, 'subsample': 0.7922526868008696, 'colsample_bytree': 0.6497688416690072, 'min_child_weight': 1, 'gamma': 3.2404027170427927, 'reg_alpha': 4.7083480807974345, 'reg_lambda': 7.471878272117835}. Best is trial 19 with value: 0.6787925435373627.

Best trial: 19. Best value: 0.678793:  68%|██████▊   | 27/40 [19:56<08:34, 39.62s/it]

[I 2026-09-13 22:59:30,696] Trial 26 finished with value: 0.6784031648908413 and parameters: {'n_estimators': 469, 'max_depth': 3, 'learning_rate': 0.04736612889771417, 'subsample': 0.7795436615765908, 'colsample_bytree': 0.782157843600622, 'min_child_weight': 6, 'gamma': 4.073415634996423, 'reg_alpha': 4.434265862921368, 'reg_lambda': 7.180534496153383}. Best is trial 19 with value: 0.6787925435373627.

Best trial: 27. Best value: 0.678954:  70%|███████   | 28/40 [20:31<07:40, 38.36s/it]

[I 2026-09-13 23:00:06,139] Trial 27 finished with value: 0.6789542015341936 and parameters: {'n_estimators': 481, 'max_depth': 3, 'learning_rate': 0.05961017798747957, 'subsample': 0.740431414940208, 'colsample_bytree': 0.6463185408534138, 'min_child_weight': 8, 'gamma': 3.8573854777223713, 'reg_alpha': 3.6694553900197353, 'reg_lambda': 8.802452936968464}. Best is trial 27 with value: 0.6789542015341936.

Best trial: 27. Best value: 0.678954:  72%|███████▎  | 29/40 [21:02<06:36, 36.08s/it]

[I 2026-09-13 23:00:36,885] Trial 28 finished with value: 0.6782053079243082 and parameters: {'n_estimators': 416, 'max_depth': 3, 'learning_rate': 0.09151069053997724, 'subsample': 0.7975888096658212, 'colsample_bytree': 0.6074812865435215, 'min_child_weight': 7, 'gamma': 3.287427902215913, 'reg_alpha': 4.083834358687986, 'reg_lambda': 6.070805216337254}. Best is trial 27 with value: 0.6789542015341936.

Best trial: 27. Best value: 0.678954:  75%|███████▌  | 30/40 [21:50<06:34, 39.49s/it]

[I 2026-09-13 23:01:24,354] Trial 29 finished with value: 0.6750185685845619 and parameters: {'n_estimators': 608, 'max_depth': 4, 'learning_rate': 0.07264874782155474, 'subsample': 0.7278684737498886, 'colsample_bytree': 0.7503952800213122, 'min_child_weight': 3, 'gamma': 3.309883182443623, 'reg_alpha': 4.89581047464938, 'reg_lambda': 8.929415713974908}. Best is trial 27 with value: 0.6789542015341936.

Best trial: 27. Best value: 0.678954:  78%|███████▊  | 31/40 [22:17<05:21, 35.74s/it]

[I 2026-09-13 23:01:51,334] Trial 30 finished with value: 0.6780829264315726 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.052935324664505, 'subsample': 0.8318172353190727, 'colsample_bytree': 0.7272146069282274, 'min_child_weight': 3, 'gamma': 2.600417781705545, 'reg_alpha': 3.39227002877032, 'reg_lambda': 7.856347133280002}. Best is trial 27 with value: 0.6789542015341936.

Best trial: 27. Best value: 0.678954:  80%|████████  | 32/40 [22:59<05:02, 37.75s/it]

[I 2026-09-13 23:02:33,780] Trial 31 finished with value: 0.6783132377115377 and parameters: {'n_estimators': 618, 'max_depth': 3, 'learning_rate': 0.06754707225311708, 'subsample': 0.8246913411586021, 'colsample_bytree': 0.7617738407758317, 'min_child_weight': 1, 'gamma': 2.1699023559634427, 'reg_alpha': 4.212253984307071, 'reg_lambda': 7.068548222080704}. Best is trial 27 with value: 0.6789542015341936.

Best trial: 27. Best value: 0.678954:  82%|████████▎ | 33/40 [23:32<04:14, 36.29s/it]

[I 2026-09-13 23:03:06,663] Trial 32 finished with value: 0.6785014880044782 and parameters: {'n_estimators': 439, 'max_depth': 3, 'learning_rate': 0.06552500253740723, 'subsample': 0.8135447053656306, 'colsample_bytree': 0.7064454639149031, 'min_child_weight': 4, 'gamma': 3.9928267527348487, 'reg_alpha': 4.5400500480343675, 'reg_lambda': 8.60538455008568}. Best is trial 27 with value: 0.6789542015341936.

Best trial: 27. Best value: 0.678954:  85%|████████▌ | 34/40 [24:30<04:17, 42.95s/it]

[I 2026-09-13 23:04:05,148] Trial 33 finished with value: 0.6786967869459232 and parameters: {'n_estimators': 530, 'max_depth': 3, 'learning_rate': 0.04783107552869764, 'subsample': 0.7257351464202144, 'colsample_bytree': 0.660582340884429, 'min_child_weight': 10, 'gamma': 4.285428610117039, 'reg_alpha': 3.223892938876028, 'reg_lambda': 8.849404055474908}. Best is trial 27 with value: 0.6789542015341936.

Best trial: 27. Best value: 0.678954:  88%|████████▊ | 35/40 [25:07<03:25, 41.05s/it]

[I 2026-09-13 23:04:41,752] Trial 34 finished with value: 0.6784742418261734 and parameters: {'n_estimators': 503, 'max_depth': 3, 'learning_rate': 0.06247736196638214, 'subsample': 0.7993010984933564, 'colsample_bytree': 0.6318954120554061, 'min_child_weight': 9, 'gamma': 4.257066928251204, 'reg_alpha': 2.92524370595003, 'reg_lambda': 6.595376687890845}. Best is trial 27 with value: 0.6789542015341936.

Best trial: 27. Best value: 0.678954:  90%|█████████ | 36/40 [25:41<02:35, 38.85s/it]

[I 2026-09-13 23:05:15,470] Trial 35 finished with value: 0.6782992369456413 and parameters: {'n_estimators': 509, 'max_depth': 3, 'learning_rate': 0.0448378631861261, 'subsample': 0.806787233199374, 'colsample_bytree': 0.6445698713091719, 'min_child_weight': 9, 'gamma': 3.2975383417116078, 'reg_alpha': 4.539172079645034, 'reg_lambda': 8.721771611409665}. Best is trial 27 with value: 0.6789542015341936.

Best trial: 27. Best value: 0.678954:  92%|█████████▎| 37/40 [26:19<01:55, 38.62s/it]

[I 2026-09-13 23:05:53,562] Trial 36 finished with value: 0.6787663103923229 and parameters: {'n_estimators': 517, 'max_depth': 3, 'learning_rate': 0.06796862472206652, 'subsample': 0.7056070788161017, 'colsample_bytree': 0.7021590855060408, 'min_child_weight': 8, 'gamma': 4.209300465573013, 'reg_alpha': 3.860459440823427, 'reg_lambda': 8.294081957593308}. Best is trial 27 with value: 0.6789542015341936.

Best trial: 27. Best value: 0.678954:  95%|█████████▌| 38/40 [26:56<01:16, 38.28s/it]

[I 2026-09-13 23:06:31,038] Trial 37 finished with value: 0.6782545816726094 and parameters: {'n_estimators': 515, 'max_depth': 3, 'learning_rate': 0.07674318979530595, 'subsample': 0.8042279277856276, 'colsample_bytree': 0.7272752372526404, 'min_child_weight': 6, 'gamma': 2.462352343287781, 'reg_alpha': 4.466241198575696, 'reg_lambda': 8.141356438838862}. Best is trial 27 with value: 0.6789542015341936.

Best trial: 27. Best value: 0.678954:  98%|█████████▊| 39/40 [27:37<00:39, 39.00s/it]

[I 2026-09-13 23:07:11,722] Trial 38 finished with value: 0.6785621359238923 and parameters: {'n_estimators': 447, 'max_depth': 3, 'learning_rate': 0.0663712256600156, 'subsample': 0.6563764113826529, 'colsample_bytree': 0.6854590568005738, 'min_child_weight': 9, 'gamma': 4.661334668177148, 'reg_alpha': 3.4020558122642264, 'reg_lambda': 7.906225227071772}. Best is trial 27 with value: 0.6789542015341936.

Best trial: 27. Best value: 0.678954: 100%|██████████| 40/40 [28:37<00:00, 42.95s/it]

[I 2026-09-13 23:08:11,961] Trial 39 finished with value: 0.6786271506658174 and parameters: {'n_estimators': 496, 'max_depth': 3, 'learning_rate': 0.06116692112615616, 'subsample': 0.6601716494005165, 'colsample_bytree': 0.7475591828686647, 'min_child_weight': 9, 'gamma': 4.917224541430826, 'reg_alpha': 3.1037952658112777, 'reg_lambda': 9.274326099831775}. Best is trial 27 with value: 0.6789542015341936.

📊 BEST CV AUC: 0.67895
BEST PARAMS: {'n_estimators': 481, 'max_depth': 3, 'learning_rate': 0.05961017798747957, 'subsample': 0.740431414940208, 'colsample_bytree': 0.6463185408534138, 'min_child_weight': 8, 'gamma': 3.8573854777223713, 'reg_alpha': 3.6694553900197353, 'reg_lambda': 8.802452936968464}

In [39]:
# ============================================================
#  MULTI-MODEL COMPARISON + ENSEMBLE
# ============================================================
import numpy as np
from scipy.stats import rankdata
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

# ---- data ----
X = train[feature_cols]
y = train['TARGET']
spw = float((y == 0).sum() / (y == 1).sum())   # plain float (avoids CatBoost clone bug)
print("scale_pos_weight:", round(spw, 2))

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# ============================================================
# 1. XGBOOST (best tuned params from Optuna)
# ============================================================
xgb_params = {
    'n_estimators': 481, 'max_depth': 3, 'learning_rate': 0.05961,
    'subsample': 0.74043, 'colsample_bytree': 0.64632,
    'min_child_weight': 8, 'gamma': 3.85739,
    'reg_alpha': 3.66946, 'reg_lambda': 8.80245,
    'scale_pos_weight': spw, 'eval_metric': 'auc',
    'random_state': 42, 'n_jobs': -1,
}
xgb = XGBClassifier(**xgb_params)
oof_xgb = cross_val_predict(xgb, X, y, cv=cv, method='predict_proba', n_jobs=-1)[:, 1]
print("XGBoost  CV AUC:", round(roc_auc_score(y, oof_xgb), 5))

# ============================================================
# 2. LIGHTGBM
# ============================================================
lgb = LGBMClassifier(
    n_estimators=500, max_depth=3, num_leaves=8,
    learning_rate=0.05, subsample=0.75, colsample_bytree=0.65,
    reg_alpha=3.5, reg_lambda=8.5, min_child_samples=40,
    scale_pos_weight=spw, random_state=42, n_jobs=-1, verbose=-1
)
oof_lgb = cross_val_predict(lgb, X, y, cv=cv, method='predict_proba', n_jobs=-1)[:, 1]
print("LightGBM CV AUC:", round(roc_auc_score(y, oof_lgb), 5))

# ============================================================
# 3. CATBOOST  (n_jobs=1 -> CatBoost handles its own threads)
# ============================================================
cat = CatBoostClassifier(
    iterations=500, depth=3, learning_rate=0.05,
    l2_leaf_reg=8, subsample=0.75,
    scale_pos_weight=spw, random_state=42,
    verbose=0, allow_writing_files=False
)
oof_cat = cross_val_predict(cat, X, y, cv=cv, method='predict_proba', n_jobs=1)[:, 1]
print("CatBoost CV AUC:", round(roc_auc_score(y, oof_cat), 5))

# ============================================================
# 4. ENSEMBLE
# ============================================================
print("\n---- model correlations (lower = more diverse) ----")
print("corr xgb-lgb:", round(np.corrcoef(oof_xgb, oof_lgb)[0, 1], 4))
print("corr xgb-cat:", round(np.corrcoef(oof_xgb, oof_cat)[0, 1], 4))
print("corr lgb-cat:", round(np.corrcoef(oof_lgb, oof_cat)[0, 1], 4))

# simple average
blend = (oof_xgb + oof_lgb + oof_cat) / 3
print("\n🎯 BLEND      CV AUC:", round(roc_auc_score(y, blend), 5))

# rank average (usually best for AUC since AUC is rank-based)
rank_blend = (rankdata(oof_xgb) + rankdata(oof_lgb) + rankdata(oof_cat)) / 3
print("🎯 RANK-BLEND CV AUC:", round(roc_auc_score(y, rank_blend), 5))

# ---- summary table ----
print("\n================ SUMMARY ================")
for name, oof in [('XGBoost', oof_xgb), ('LightGBM', oof_lgb),
                  ('CatBoost', oof_cat), ('Blend', blend),
                  ('Rank-Blend', rank_blend)]:
    print(f"{name:12s}: {roc_auc_score(y, oof):.5f}")

scale_pos_weight: 11.41
XGBoost  CV AUC: 0.67892
LightGBM CV AUC: 0.6781
CatBoost CV AUC: 0.67752

---- model correlations (lower = more diverse) ----
corr xgb-lgb: 0.9878
corr xgb-cat: 0.9817
corr lgb-cat: 0.985

🎯 BLEND      CV AUC: 0.67898
🎯 RANK-BLEND CV AUC: 0.67896

================ SUMMARY ================
XGBoost     : 0.67892
LightGBM    : 0.67810
CatBoost    : 0.67752
Blend       : 0.67898
Rank-Blend  : 0.67896

In [2]:
# ============================================================
#  OPTIMIZATION: feature selection + spw sweep + ensemble + submission
# ============================================================
import numpy as np, pandas as pd, os
from scipy.stats import rankdata
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

# make sure we're on the clean 69 features
train = pd.read_csv('features_train.csv')
test  = pd.read_csv('features_test.csv')
feature_cols = [c for c in train.columns if c not in ['uid','TARGET','NAME_CONTRACT_TYPE']]
for c in feature_cols:
    if c not in test.columns: test[c] = 0
test = test[['uid'] + feature_cols]

y   = train['TARGET']
spw = float((y==0).sum()/(y==1).sum())
cv  = StratifiedKFold(5, shuffle=True, random_state=42)

BEST = dict(n_estimators=481, max_depth=3, learning_rate=0.05961,
            subsample=0.74043, colsample_bytree=0.64632,
            min_child_weight=8, gamma=3.85739,
            reg_alpha=3.66946, reg_lambda=8.80245,
            eval_metric='auc', random_state=42, n_jobs=-1)

def cv_auc(params, cols):
    m = XGBClassifier(**params)
    oof = cross_val_predict(m, train[cols], y, cv=cv,
                            method='predict_proba', n_jobs=-1)[:,1]
    return roc_auc_score(y, oof), oof

# ---------- STEP 1: scale_pos_weight sweep ----------
print("STEP 1 — spw sweep")
best_spw, best_auc = spw, 0
for w in [1.0, spw**0.5, spw*0.5, spw]:
    a,_ = cv_auc({**BEST,'scale_pos_weight':w}, feature_cols)
    print(f"  spw={w:6.2f}  AUC={a:.5f}")
    if a > best_auc: best_auc, best_spw = a, w
BEST['scale_pos_weight'] = best_spw
print(f"  -> best spw={best_spw:.2f}  AUC={best_auc:.5f}\n")

# ---------- STEP 2: feature selection ----------
print("STEP 2 — feature selection")
m = XGBClassifier(**BEST).fit(train[feature_cols], y)
imp = pd.Series(m.feature_importances_, index=feature_cols)
base_auc,_ = cv_auc(BEST, feature_cols)
print(f"  all {len(feature_cols)} feats: AUC={base_auc:.5f}")
best_cols, best_sel = feature_cols, base_auc
for q in [0.10, 0.20, 0.30]:
    keep = imp[imp > imp.quantile(q)].index.tolist()
    a,_ = cv_auc(BEST, keep)
    print(f"  drop bottom {int(q*100)}% -> {len(keep)} feats: AUC={a:.5f}")
    if a > best_sel: best_sel, best_cols = a, keep
print(f"  -> kept {len(best_cols)} feats  AUC={best_sel:.5f}\n")

# ---------- STEP 3: 3-model rank-blend on chosen config ----------
print("STEP 3 — ensemble on selected features")
Xtr = train[best_cols]

xgb = XGBClassifier(**BEST)
oof_x = cross_val_predict(xgb, Xtr, y, cv=cv, method='predict_proba', n_jobs=-1)[:,1]

lgb = LGBMClassifier(n_estimators=500, max_depth=3, num_leaves=8,
        learning_rate=0.05, subsample=0.75, colsample_bytree=0.65,
        reg_alpha=3.5, reg_lambda=8.5, min_child_samples=40,
        scale_pos_weight=best_spw, random_state=42, n_jobs=-1, verbose=-1)
oof_l = cross_val_predict(lgb, Xtr, y, cv=cv, method='predict_proba', n_jobs=-1)[:,1]

cat = CatBoostClassifier(iterations=500, depth=3, learning_rate=0.05,
        l2_leaf_reg=8, subsample=0.75, scale_pos_weight=best_spw,
        random_state=42, verbose=0, allow_writing_files=False)
oof_c = cross_val_predict(cat, Xtr, y, cv=cv, method='predict_proba', n_jobs=1)[:,1]

print(f"  XGB={roc_auc_score(y,oof_x):.5f}  LGB={roc_auc_score(y,oof_l):.5f}  CAT={roc_auc_score(y,oof_c):.5f}")
rank_blend = (rankdata(oof_x)+rankdata(oof_l)+rankdata(oof_c))/3
blend_auc  = roc_auc_score(y, rank_blend)
print(f"  RANK-BLEND AUC={blend_auc:.5f}")

# pick the best of {xgb-alone, blend}
use_blend = blend_auc > roc_auc_score(y, oof_x)
final_auc = blend_auc if use_blend else roc_auc_score(y, oof_x)
print(f"\n🏆 FINAL CV AUC = {final_auc:.5f}  ({'rank-blend' if use_blend else 'xgb-only'})")

# ---------- STEP 4: fit on full data, predict test, submission ----------
print("\nSTEP 4 — submission")
xgb_f = XGBClassifier(**BEST).fit(Xtr, y)
pred_x = xgb_f.predict_proba(test[best_cols])[:,1]

if use_blend:
    lgb_f = lgb.fit(Xtr, y); pred_l = lgb_f.predict_proba(test[best_cols])[:,1]
    cat_f = cat.fit(Xtr, y); pred_c = cat_f.predict_proba(test[best_cols])[:,1]
    test_pred = (rankdata(pred_x)+rankdata(pred_l)+rankdata(pred_c))/(3*len(pred_x))
else:
    test_pred = pred_x

sub = pd.DataFrame({'uid': test['uid'], 'TARGET': test_pred})
out_dir = r'E:\senior_ds_test\senior_ds_test\final_submission'
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, 'final_submission_Sakshi_Vedi.csv')
sub.to_csv(out_path, index=False)
print("  saved:", out_path)
print(sub.head())

STEP 1 — spw sweep
  spw=  1.00  AUC=0.67951
  spw=  3.38  AUC=0.67928
  spw=  5.71  AUC=0.67928
  spw= 11.41  AUC=0.67892
  -> best spw=1.00  AUC=0.67951

STEP 2 — feature selection
  all 69 feats: AUC=0.67951
  drop bottom 10% -> 61 feats: AUC=0.68003
  drop bottom 20% -> 55 feats: AUC=0.67990
  drop bottom 30% -> 48 feats: AUC=0.68019
  -> kept 48 feats  AUC=0.68019

STEP 3 — ensemble on selected features
  XGB=0.68019  LGB=0.67956  CAT=0.67747
  RANK-BLEND AUC=0.67985

🏆 FINAL CV AUC = 0.68019  (xgb-only)

STEP 4 — submission
  saved: E:\senior_ds_test\senior_ds_test\final_submission\final_submission_Sakshi_Vedi.csv
           uid    TARGET
0  CMO22835242  0.041475
1  MRJ34316727  0.167568
2  UAV00534378  0.075144
3  IPQ08190402  0.066599
4  NQN84331006  0.056035